# Generated by Django 4.2.19 on 2025-03-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='Sweden', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='street_address',
            field=models.CharField(default='123 Crispy street', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='town_or_city',
            field=models.CharField(default='Gothenburg', max_length=40),
        ),
    ]
