# Generated by Django 4.2.19 on 2025-03-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribedusers',
            options={'verbose_name_plural': 'Subscribed users'},
        ),
    ]
